server:
  port: 8080
spring:
  application:
    name: reggie # 应用名称
  datasource: # 数据源配置
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
  redis:
    host: localhost
    port: 6379
    database: 0
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true # 驼峰命名法映射 address_book ---> AddressBook
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志输出
#  mapper-locations: classpath:/mappers/**.xml # 指定xml位置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mappers/**.xml
  global-config:
    db-config:
      id-type: ASSIGN_ID # id生成策略类型